version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile

      - run:
          name: Run linters
          command: yarn lint

      - run:
          name: Build website
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then \
              WEBSITE_ROOT_URL=https://pscanf.com/ yarn build \
            ; else \
              WEBSITE_ROOT_URL=https://pscanf.com/_/$CIRCLE_BRANCH/ yarn build \
            ; fi

      - run:
          name: Install staticdeploy cli
          command: |
            yarn global add @staticdeploy/cli
            echo 'export PATH=$PATH:$(yarn global bin)' >> $BASH_ENV

      - run:
          name: Create website bundle
          command: |
            staticdeploy create-bundle \
              --from dist \
              --name pscanf.com \
              --tag $CIRCLE_BRANCH \
              --description "Commit $CIRCLE_SHA1" \
              --fallbackAssetPath /404.html

      - run:
          name: Deploy website bundle to pscanf.com/ or pscanf.com/_/branch
          command: |
            if [ $CIRCLE_BRANCH = "master" ]; then \
              staticdeploy deploy \
                --app pscanf.com \
                --entrypoint pscanf.com/ \
                --bundle pscanf.com:$CIRCLE_BRANCH \
            ; else \
              staticdeploy deploy \
                --app pscanf.com \
                --entrypoint pscanf.com/_/$CIRCLE_BRANCH/ \
                --bundle pscanf.com:$CIRCLE_BRANCH \
            ; fi
